### PR TITLE
Define format for output

### PR DESCRIPTION
**Pull request by Sharaal**
Because millisecond is not the only format which is needed (e.g. redis expire wants the duration in seconds), I added the opportunity to define the output format.

So instead of:
```js
const m = parse('1hr 20mins') / 1000 / 60;
```

You can do:
```js
const m = parse('1hr 20mins', 'm');
```

### CODE REVIEW

**Comment by dragonprojects** [comment]
See also: https://github.com/dnode/dparse-duration
If someone also needed this functionality and the PR won't be merged, feel free to use it. :)

**Comment by fruch** [comment]
@sharaal looks like a good idea to me.

just out of curiosity, why did you limit to node 7 and up in you version of the package ?

**Comment by Sharaal** [comment]
@fruch Thats not a needed limit for this package. 
I have it in all my packages as standard because of async/await (without transpiler) which needs minimum v7.6.

**Comment by dy** [comment]
Thanks, merged/published.

**Pull request merged**
